name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions: { }

jobs:
  gradle:
    uses: tacascer-org/actions-workflows/.github/workflows/gradle_build.yml@v0
    with:
      java-version: 21
    secrets: inherit
    permissions:
      security-events: write
      contents: write
      statuses: write
